name:                codegame
version:             0.1.0.0
github:              "Atrongant/codegame"
license:             BSD3
author:              "mywen"
maintainer:          "402635876@qq.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Atrongant/codegame#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- classy-prelude
- http-types
- bytestring
- utf8-string
- blaze-builder
- resourcet
- text
- wai-extra
- aeson
- amazonka-core
- tagstream-conduit
- process
- containers
- strict
- mysql-haskell
- io-streams
- transformers
- persistent-mysql 
- persistent 
- persistent-template 
- monad-logger 
- esqueleto 
- MonadRandom
- uuid
- password-instances
- hedis
- safe-exceptions
- cookie
- time-lens
- time
- directory
default-extensions:
- NoImplicitPrelude
- OverloadedStrings  
- EmptyDataDecls
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- QuasiQuotes
- TemplateHaskell
- TypeFamilies
- TypeSynonymInstances
- DeriveGeneric
- ConstraintKinds  

library:
  source-dirs: src

executables:
  codegame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codegame
    # - wai
    # - warp
    # - http-types

tests:
  codegame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codegame
    # - wai
    # - warp
    # - http-types
